name: GCP Image Push

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup gcloud
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure docker for GCP
      run: gcloud auth configure-docker

    - name: Build docker image
      run:  docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/bitzer-me-static-site:latest . 

    - name: Push to Google Container Registry
      run:  docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/bitzer-me-static-site:latest 